#!/bin/bash
set -e

# Install Golang
if ! command -v go &> /dev/null; then
  echo "Golang not found, installing..."
  wget https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz
  sudo tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
  export PATH=$PATH:/usr/local/go/bin
else
  echo "Golang already installed"
fi

# Set GOPATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
