#!/bin/bash
set -e

# Create a temporary directory for Golang installation
TEMP_GO_DIR=$(mktemp -d)
echo "Installing Golang in temporary directory: $TEMP_GO_DIR"

# Download and extract Golang
wget https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz -O $TEMP_GO_DIR/go1.16.5.linux-amd64.tar.gz
tar -C $TEMP_GO_DIR -xzf $TEMP_GO_DIR/go1.16.5.linux-amd64.tar.gz

# Add Golang to PATH
export PATH=$TEMP_GO_DIR/go/bin:$PATH

# Set GOPATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

go version

CONTROLLER_DIR=$(pwd)/..